from typing import Optional

class PgQueryExc(Exception):
    def __init__(
        self, message: str, function: str, filename: str, lineno: int, cursorpos: int, context: Optional[str] = ...
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

def query_normalize(query: str) -> str: ...
def query_parse_json(query: str) -> str: ...
def query_parse_protobuf(query: str) -> bytearray: ...
def query_deparse_protobuf(pb_bytes: bytes) -> str: ...
